/*{"created":"2010-11-11T04:35:23Z","mac":"1:cf6bcea6932921141d733617494cc92e209821501a33de5b668eef4cfc4cb0ea","k":"0.7.18","version":"1200078"}*/
;(function(window,document,undefined){
function n(a){return function(){return this[a]}}var p;function q(a,b){this.p=a;this.i=b}p=q.prototype;p.createElement=function(a,b,c){a=this.p.createElement(a);if(b)for(var d in b)if(b.hasOwnProperty(d))if(d=="style"&&this.i.getName()=="MSIE")a.style.cssText=b[d];else a.setAttribute(d,b[d]);c&&a.appendChild(this.p.createTextNode(c));return a};p.insertInto=function(a,b){a=this.p.getElementsByTagName(a)[0];if(!a)a=document.documentElement;if(a&&a.lastChild){a.insertBefore(b,a.lastChild);return true}return false};
p.whenBodyExists=function(a){function b(){document.body?a():setTimeout(b,0)}b()};p.removeElement=function(a){if(a.parentNode){a.parentNode.removeChild(a);return true}return false};p.createCssLink=function(a){return this.createElement("link",{rel:"stylesheet",href:a})};p.appendClassName=function(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/^\s+/,"")};
p.removeClassName=function(a,b){for(var c=a.className.split(/\s+/),d=[],e=0,h=c.length;e<h;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")};function r(a,b,c,d,e,h,i,g){this.fa=a;this.oa=b;this.$=c;this.Z=d;this.ia=e;this.ha=h;this.Y=i;this.pa=g}p=r.prototype;p.getName=n("fa");p.getVersion=n("oa");p.getEngine=n("$");p.getEngineVersion=n("Z");p.getPlatform=n("ia");p.getPlatformVersion=n("ha");p.getDocumentMode=n("Y");function s(a,b){this.i=a;this.r=b}
var aa=new r("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",undefined,false);s.prototype.parse=function(){return this.i.indexOf("MSIE")!=-1?ba(this):this.i.indexOf("Opera")!=-1?ca(this):this.i.indexOf("AppleWebKit")!=-1?da(this):this.i.indexOf("Gecko")!=-1?ea(this):aa};function t(a){var b=u(a,a.i,/(iPod|iPad|iPhone|Android)/,1);if(b!="")return b;a=u(a,a.i,/(Linux|Mac_PowerPC|Macintosh|Windows)/,1);if(a!=""){if(a=="Mac_PowerPC")a="Macintosh";return a}return"Unknown"}
function v(a){var b=u(a,a.i,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b)return b;if(b=u(a,a.i,/(iPhone )?OS ([\d_]+)/,2))return b;if(a=u(a,a.i,/Linux ([i\d]+)/,1))return a;return"Unknown"}function ba(a){var b=u(a,a.i,/(MSIE [\d\w\.]+)/,1);if(b!=""){var c=b.split(" ");b=c[0];c=c[1];return new r(b,c,b,c,t(a),v(a),w(a,a.r),x(a,c)>=6)}return new r("MSIE","Unknown","MSIE","Unknown",t(a),v(a),w(a,a.r),false)}
function ca(a){var b="Unknown",c="Unknown",d=u(a,a.i,/(Presto\/[\d\w\.]+)/,1);if(d!=""){c=d.split("/");b=c[0];c=c[1]}else{if(a.i.indexOf("Gecko")!=-1)b="Gecko";d=u(a,a.i,/rv:([^\)]+)/,1);if(d!="")c=d}if(a.i.indexOf("Version/")!=-1){d=u(a,a.i,/Version\/([\d\.]+)/,1);if(d!="")return new r("Opera",d,b,c,t(a),v(a),w(a,a.r),x(a,d)>=10)}d=u(a,a.i,/Opera[\/ ]([\d\.]+)/,1);if(d!="")return new r("Opera",d,b,c,t(a),v(a),w(a,a.r),x(a,d)>=10);return new r("Opera","Unknown",b,c,t(a),v(a),w(a,a.r),false)}
function da(a){var b=t(a),c=v(a),d=u(a,a.i,/AppleWebKit\/([\d\.\+]+)/,1);if(d=="")d="Unknown";var e="Unknown";if(a.i.indexOf("Chrome")!=-1)e="Chrome";else if(a.i.indexOf("Safari")!=-1)e="Safari";else if(a.i.indexOf("AdobeAIR")!=-1)e="AdobeAIR";var h="Unknown";if(a.i.indexOf("Version/")!=-1)h=u(a,a.i,/Version\/([\d\.\w]+)/,1);else if(e=="Chrome")h=u(a,a.i,/Chrome\/([\d\.]+)/,1);else if(e=="AdobeAIR")h=u(a,a.i,/AdobeAIR\/([\d\.]+)/,1);var i=false;if(e=="AdobeAIR"){i=u(a,h,/\d+\.(\d+)/,1);i=x(a,h)>2||
x(a,h)==2&&parseInt(i,10)>=5}else{i=u(a,d,/\d+\.(\d+)/,1);i=x(a,d)>=526||x(a,d)>=525&&parseInt(i,10)>=13}return new r(e,h,"AppleWebKit",d,b,c,w(a,a.r),i)}
function ea(a){var b="Unknown",c="Unknown",d=false;if(a.i.indexOf("Firefox")!=-1){b="Firefox";var e=u(a,a.i,/Firefox\/([\d\w\.]+)/,1);if(e!=""){d=u(a,e,/\d+\.(\d+)/,1);c=e;d=e!=""&&x(a,e)>=3&&parseInt(d,10)>=5}}else if(a.i.indexOf("Mozilla")!=-1)b="Mozilla";e=u(a,a.i,/rv:([^\)]+)/,1);if(e=="")e="Unknown";else if(!d){d=x(a,e);var h=parseInt(u(a,e,/\d+\.(\d+)/,1),10),i=parseInt(u(a,e,/\d+\.\d+\.(\d+)/,1),10);d=d>1||d==1&&h>9||d==1&&h==9&&i>=2||e.match(/1\.9\.1b[123]/)!=null||e.match(/1\.9\.1\.[\d\.]+/)!=
null}return new r(b,c,"Gecko",e,t(a),v(a),w(a,a.r),d)}function x(a,b){a=u(a,b,/(\d+)/,1);if(a!="")return parseInt(a,10);return-1}function u(a,b,c,d){if((a=b.match(c))&&a[d])return a[d];return""}function w(a,b){if(b.documentMode)return b.documentMode}function fa(a,b,c,d){this.j=a;this.l=b;this.K=c;this.o=d||ga;this.n=new y("-")}var ga="wf";function z(a,b,c){a.j.removeClassName(a.l,a.n.m(a.o,b,c,"loading"));a.j.appendClassName(a.l,a.n.m(a.o,b,c,"active"));A(a,"fontactive",b,c)}
function C(a){a.j.removeClassName(a.l,a.n.m(a.o,"loading"));a.j.appendClassName(a.l,a.n.m(a.o,"inactive"));A(a,"inactive")}function ha(a){a.j.removeClassName(a.l,a.n.m(a.o,"loading"));a.j.appendClassName(a.l,a.n.m(a.o,"active"));A(a,"active")}function A(a,b,c,d){a.K[b]&&a.K[b](c,d)}function D(a,b,c,d,e){this.j=a;this.s=b;this.F=c;this.v=d;this.P=e;this.L=0;this.I=this.S=false;this.ea=new E;this.aa=new F}
D.prototype.watch=function(a,b,c,d){for(var e=a.length,h=0;h<e;h++){var i=a[h];b[i]||(b[i]=["n4"]);this.L+=b[i].length}if(d)this.S=d;for(h=0;h<e;h++){i=a[h];d=b[i];for(var g=c[i]||"Mm",f=0,l=d.length;f<l;f++){var m=d[f],o=G(this,"_,arial,helvetica",m,g),j=this.F.G(o);this.j.removeElement(o);o=i;var k=this.s;k.j.appendClassName(k.l,k.n.m(k.o,o,m,"loading"));A(k,"fontloading",o,m);k=G(this,this.ea.quote(o),m,g);if(j!=this.F.G(k)){this.j.removeElement(k);z(this.s,o,m);this.I=true;H(this)}else I(this,
this.P(),j,k,o,m)}}};function H(a){if(--a.L==0&&a.S)a.I?ha(a.s):C(a.s)}D.prototype.X=function(a,b,c,d,e){if(b!=this.F.G(c)){this.j.removeElement(c);z(this.s,d,e);this.I=true;H(this)}else if(this.P()-a<5E3)I(this,a,b,c,d,e);else{this.j.removeElement(c);a=this.s;a.j.removeClassName(a.l,a.n.m(a.o,d,e,"loading"));a.j.appendClassName(a.l,a.n.m(a.o,d,e,"inactive"));A(a,"fontinactive",d,e);H(this)}};function I(a,b,c,d,e,h){a.v(function(i,g){return function(){g.call(i,b,c,d,e,h)}}(a,a.X),50)}
function G(a,b,c,d){c=a.aa.expand(c);b=a.j.createElement("span",{style:"position:absolute;top:-999px;font-size:300px;font-family:"+b+",_,arial,helvetica;"+c},d);a.j.insertInto("body",b);return b}function y(a){this.ca=a||ia}var ia="-";y.prototype.m=function(){for(var a=[],b=0;b<arguments.length;b++)a.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return a.join(this.ca)};function E(){this.V='"'}
E.prototype.quote=function(a){var b=[];a=a.split(/,\s*/);for(var c=0;c<a.length;c++){var d=a[c].replace(/['"]/g,"");d.indexOf(" ")==-1?b.push(d):b.push(this.V+d+this.V)}return b.join(",")};function F(){this.U=ja;this.w=ka}var ja=["font-style","font-weight"],ka={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function J(a,b,c){this.ba=a;this.ja=b;this.w=c}J.prototype.expand=function(a,b){for(var c=0;c<this.w.length;c++)if(b==this.w[c][0]){a[this.ba]=this.ja+":"+this.w[c][1];return}};F.prototype.expand=function(a){if(a.length!=2)return null;for(var b=[null,null],c=0,d=this.U.length;c<d;c++){var e=this.U[c],h=a.substr(c,1);(new J(c,e,this.w[e])).expand(b,h)}return b[0]&&b[1]?b.join(";")+";":null};function K(a,b){this.p=a;this.i=b}K.prototype=q.prototype;
K.prototype.isHttps=function(){return this.p.location.protocol=="https:"};K.prototype.loadScript=function(a,b){var c=this.p.getElementsByTagName("head")[0];if(c){var d=this.p.createElement("script");d.src=a;var e=false;d.onload=d.onreadystatechange=function(){if(!e&&(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")){e=true;b&&b();d.onload=d.onreadystatechange=null;d.parentNode.tagName=="HEAD"&&c.removeChild(d)}};c.appendChild(d)}};
K.prototype.createStyle=function(a){var b=this.p.createElement("style");b.setAttribute("type","text/css");if(b.styleSheet)b.styleSheet.cssText=a;else b.appendChild(document.createTextNode(a));return b};function L(a,b){this.ma=a;this.M=b}function la(a){for(var b=a.ma.join(","),c=[],d=0;d<a.M.length;d++){var e=a.M[d];c.push(e.name+":"+e.value+";")}return b+"{"+c.join("")+"}"}function M(a,b){this.z=a;this.N=b}
M.prototype.watch=function(a,b,c){var d=[],e={};d.push(this.z);e[this.z]=this.N[b.getStylesheetFormatId()]||[];a.watch(d,e,{},c)};function N(a,b,c){this.na=a;this.H=b;this.ka=c}N.prototype.buildUrl=function(a,b){a=this.na&&a?"https:":"http:";var c=typeof this.H=="function"?this.H(a):this.H;return a+"//"+c+this.ka+b};
function ma(a,b,c){if(a.O){var d=function(){try{b._gat._getTracker("UA-8850781-3")._trackPageview();b.tkKitsTracked||(b.tkKitsTracked=0);b.tkKitsTracked++}catch(e){}};if(b._gat)d();else{a=a.O.buildUrl(c.isHttps(),"/ga.js");c.loadScript(a,d)}}}function O(a,b,c){this.u=a;this.W=b;this.R=c}O.prototype.getId=n("u");O.prototype.getStylesheetFormatId=n("W");
O.prototype.isUserAgent=function(a){return this.R?this.R(a.getName(),a.getVersion(),a.getEngine(),a.getEngineVersion(),a.getPlatform(),a.getPlatformVersion(),a.getDocumentMode()):false};O.prototype.buildCssUrl=function(a,b,c,d){c="/"+c+"-"+this.W+".css";if(d)c+="?"+d;return b.buildUrl(a,c)};function P(){this.q=[]}P.prototype.addBrowser=function(a){this.getBrowserById(a.getId())||this.q.push(a)};P.prototype.getBrowserById=function(a){for(var b=0;b<this.q.length;b++){var c=this.q[b];if(a===c.getId())return c}return null};
P.prototype.findBrowser=function(a){for(var b=0;b<this.q.length;b++){var c=this.q[b];if(c.isUserAgent(a))return c}return null};P.prototype.addBrowsersToBrowserSet=function(a){for(var b=0;b<this.q.length;b++)a.addBrowser(this.q[b])};function Q(a){this.u=a;this.C=new P;this.t=[];this.D=[]}p=Q.prototype;p.getId=n("u");p.setSecurityToken=function(a){this.la=a};p.setNestedUrl=function(a){this.ga=a};p.setKitOptions=function(a){this.A=a};p.addBrowser=function(a){this.C.addBrowser(a)};p.addFontFamily=function(a){this.t.push(a)};
p.addCssRule=function(a){this.D.push(a)};p.supportsBrowser=function(a){return!!this.C.getBrowserById(a.getId())};p.addBrowsersToBrowserSet=function(a){this.C.addBrowsersToBrowserSet(a)};p.init=function(a){for(var b=[],c=0;c<this.D.length;c++)b.push(la(this.D[c]));a.insertInto("head",a.createStyle(b.join("")))};
p.load=function(a,b,c,d){var e=c.buildCssUrl(a.isHttps(),this.ga,this.u,this.la);a.insertInto("head",a.createCssLink(e));b&&a.whenBodyExists(function(h,i,g,f){return function(){for(var l=0;l<h.t.length;l++)h.t[l].watch(i,g,f&&l==h.t.length-1)}}(this,b,c,d))};p.collectFontFamilies=function(a,b,c){for(var d=0;d<this.t.length;d++){var e=this.t[d];b.push(e.z);c[e.z]=e.N[a.getStylesheetFormatId()]||[]}};
p.performOptionalActions=function(a,b,c){this.A&&c.whenBodyExists(function(d,e,h,i){return function(){ma(d.A,e,i);var g=d.A,f=d.u;if(g.T){g=g.T.buildUrl(i.isHttps(),"/"+f+".js?"+ +new Date);i.loadScript(g)}f=d.A;g=d.u;if(f.J){f=f.J.m(g,h,i);f.setAttribute("id","typekit-badge-"+g);i.insertInto("body",f)}}}(this,a,b,c))};function R(a,b,c,d,e){this.da=a;this.j=b;this.i=c;this.l=d;this.v=e;this.k=[]}R.prototype.B=function(a){this.k.push(a)};
R.prototype.load=function(a,b){a=a;var c=b||{};if(typeof a=="string")a=[a];else if(a&&a.length)a=a;else{c=a||{};a=[]}if(a.length){var d=this,e=a.length;for(b=0;b<a.length;b++)na(this,a[b],function(){--e==0&&S(d,c)})}else S(this,c)};function na(a,b,c){a.j.loadScript(a.da.buildUrl(a.j.isHttps(),"/"+b+".js"),c)}
function S(a,b){if(b.userAgent)a.i=(new s(b.userAgent,document)).parse();b=new fa(a.j,a.l,b);for(var c=new P,d=0;d<a.k.length;d++)a.k[d].addBrowsersToBrowserSet(c);c=c.findBrowser(a.i);for(d=0;d<a.k.length;d++)a.k[d].init(a.j);if(c){b.j.appendClassName(b.l,b.n.m(b.o,"loading"));A(b,"loading");oa(a,c,b)}else C(b);a.k=[]}
function oa(a,b,c){c=new D(a.j,c,{G:function(h){return h.offsetWidth}},a.v,function(){return+new Date});for(var d=0;d<a.k.length;d++){var e=a.k[d];if(e.supportsBrowser(b)){e.load(a.j,c,b,d==a.k.length-1);e.performOptionalActions(window,a.i,a.j)}}}function T(a,b,c){this.Q=a;this.j=b;this.v=c;this.k=[]}T.prototype.B=function(a){this.k.push(a)};
T.prototype.load=function(){var a=this.Q.__webfonttypekitmodule__;if(a)for(var b=0;b<this.k.length;b++){var c=this.k[b],d=a[c.getId()];if(d){var e=this.j,h=this.v;d(function(i,g,f){var l=new P;c.addBrowsersToBrowserSet(l);g=[];var m={};if(l=l.findBrowser(i)){c.init(e);c.load(e,null,l,h);c.collectFontFamilies(l,g,m);c.performOptionalActions(window,i,e,h)}f(!!l,g,m)})}}};var U=new P;
U.addBrowser(new O("ie9-winvista","h",function(a,b,c,d,e,h,i){var g=false;g=g||(e=="Windows"&&h=="6.0"?true:false);if(!g)return false;return function(f,l,m,o,j,k,B){if(f=="MSIE"){if(f=/([0-9]+.[0-9]+)/.exec(l))return parseFloat(f[1])>=9&&B>=9;return false}}(a,b,c,d,e,h,i)}));
U.addBrowser(new O("chrome-linux-osx-win2003-win7-winvista-winxp","b",function(a,b,c,d,e,h,i){var g=false;g=(g=(g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="5.2"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false))||function(f,l,m,o,j,k){f=/^([0-9]+)(_|.)([0-9]+)/.exec(k);if(j=="Macintosh"&&f){j=parseInt(f[1],10);k=parseInt(f[3],10);if(j==10)return k>3;else if(j>10)return true}else return j=="Macintosh"&&k=="Unknown"?true:false}(a,b,c,
d,e,h,i))||(e=="Ubuntu"||e=="Linux"?true:false);if(!g)return false;return function(f,l){if(f=="Chrome"){var m=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(l);if(m){f=parseFloat(m[1]);l=parseInt(m[2],10);m=parseInt(m[3],10);if(f>=6)return false;else if(f>4)return true;else if(f==4&&l>249)return true;else if(f==4&&l==249&&m>=4)return true}}return false}(a,b,c,d,e,h,i)}));
U.addBrowser(new O("safari-osx-win2003-win7-winvista-winxp","b",function(a,b,c,d,e,h,i){var g=false;g=(g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="5.2"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false))||function(f,l,m,o,j,k){f=/^([0-9]+)(_|.)([0-9]+)/.exec(k);if(j=="Macintosh"&&f){j=parseInt(f[1],10);k=parseInt(f[3],10);if(j==10)return k>3;else if(j>10)return true}else return j=="Macintosh"&&k=="Unknown"?true:false}(a,b,c,d,e,h,i);
if(!g)return false;return function(f,l,m,o,j){if(f=="Safari"&&m=="AppleWebKit"||f=="Unknown"&&m=="AppleWebKit"&&(j=="iPhone"||j=="iPad"))if(f=/([0-9]+.[0-9]+)/.exec(o))return parseFloat(f[1])>=525.13;return false}(a,b,c,d,e,h,i)}));
U.addBrowser(new O("ff35-linux-osx-win2003-win7-winvista-winxp","b",function(a,b,c,d,e,h,i){var g=false;g=(g=(g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="5.2"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false))||function(f,l,m,o,j,k){f=/^([0-9]+)(_|.)([0-9]+)/.exec(k);if(j=="Macintosh"&&f){j=parseInt(f[1],10);k=parseInt(f[3],10);if(j==10)return k>3;else if(j>10)return true}else return j=="Macintosh"&&k=="Unknown"?true:false}(a,b,c,d,
e,h,i))||(e=="Ubuntu"||e=="Linux"?true:false);if(!g)return false;return function(f,l,m,o){if(m=="Gecko"){f=/1.9.1b[1-3]{1}/;return/1.9.1/.test(o)&&!f.test(o)}return false}(a,b,c,d,e,h,i)}));
U.addBrowser(new O("ff36-linux-osx-win2003-win7-winvista-winxp","e",function(a,b,c,d,e,h,i){var g=false;g=(g=(g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="5.2"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false))||function(f,l,m,o,j,k){f=/^([0-9]+)(_|.)([0-9]+)/.exec(k);if(j=="Macintosh"&&f){j=parseInt(f[1],10);k=parseInt(f[3],10);if(j==10)return k>3;else if(j>10)return true}else return j=="Macintosh"&&k=="Unknown"?true:false}(a,b,c,d,
e,h,i))||(e=="Ubuntu"||e=="Linux"?true:false);if(!g)return false;return function(f,l,m,o){if(m=="Gecko")if(l=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(o)){f=parseFloat(l[1]);l=parseInt(l[3],10);return f>1.9||f>=1.9&&l>1}return false}(a,b,c,d,e,h,i)}));
U.addBrowser(new O("chrome6-linux-osx","d",function(a,b,c,d,e,h,i){var g=false;g=(g=g||function(f,l,m,o,j,k){f=/^([0-9]+)(_|.)([0-9]+)/.exec(k);if(j=="Macintosh"&&f){j=parseInt(f[1],10);k=parseInt(f[3],10);if(j==10)return k>3;else if(j>10)return true}else return j=="Macintosh"&&k=="Unknown"?true:false}(a,b,c,d,e,h,i))||(e=="Ubuntu"||e=="Linux"?true:false);if(!g)return false;return function(f,l){if(f=="Chrome")if(f=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(l))if(parseFloat(f[1])>=6)return true}(a,b,
c,d,e,h,i)}));
U.addBrowser(new O("air-linux-osx-win","b",function(a,b,c,d,e,h,i){var g=false;g=(g=(g=g||(e=="Windows"&&h=="Unknown"?true:false))||function(f,l,m,o,j,k){f=/^([0-9]+)(_|.)([0-9]+)/.exec(k);if(j=="Macintosh"&&f){j=parseInt(f[1],10);k=parseInt(f[3],10);if(j==10)return k>3;else if(j>10)return true}else return j=="Macintosh"&&k=="Unknown"?true:false}(a,b,c,d,e,h,i))||(e=="Ubuntu"||e=="Linux"?true:false);if(!g)return false;return function(f,l){if(f=="AdobeAIR")if(f=/([0-9]+.[0-9]+)/.exec(l))return parseFloat(f[1])>=2.5;
return false}(a,b,c,d,e,h,i)}));U.addBrowser(new O("chrome6-win2003-win7-winvista-winxp","e",function(a,b,c,d,e,h,i){var g=false;g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="5.2"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false);if(!g)return false;return function(f,l){if(f=="Chrome")if(f=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(l))if(parseFloat(f[1])>=6)return true}(a,b,c,d,e,h,i)}));
U.addBrowser(new O("ie9-win7","g",function(a,b,c,d,e,h,i){var g=false;g=g||(e=="Windows"&&h=="6.1"?true:false);if(!g)return false;return function(f,l,m,o,j,k,B){if(f=="MSIE"){if(f=/([0-9]+.[0-9]+)/.exec(l))return parseFloat(f[1])>=9&&B>=9;return false}}(a,b,c,d,e,h,i)}));
U.addBrowser(new O("ie-win2003-win7-winvista-winxp","c",function(a,b,c,d,e,h,i){var g=false;g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="5.2"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false);if(!g)return false;return function(f,l,m,o,j,k,B){if(f=="MSIE"){if(f=/([0-9]+.[0-9]+)/.exec(l))return parseFloat(f[1])>=6&&(B===undefined||B<9);return false}}(a,b,c,d,e,h,i)}));
U.addBrowser(new O("opera-linux-osx-win2003-win7-winvista-winxp","b",function(a,b,c,d,e,h,i){var g=false;g=(g=(g=(g=(g=(g=g||(e=="Windows"&&h=="5.1"?true:false))||(e=="Windows"&&h=="5.2"?true:false))||(e=="Windows"&&h=="6.0"?true:false))||(e=="Windows"&&h=="6.1"?true:false))||function(f,l,m,o,j,k){f=/^([0-9]+)(_|.)([0-9]+)/.exec(k);if(j=="Macintosh"&&f){j=parseInt(f[1],10);k=parseInt(f[3],10);if(j==10)return k>3;else if(j>10)return true}else return j=="Macintosh"&&k=="Unknown"?true:false}(a,b,c,d,
e,h,i))||(e=="Ubuntu"||e=="Linux"?true:false);if(!g)return false;return a=="Opera"?parseFloat(b)>=10.54:false}));
U.addBrowser(new O("safari-android","a",function(a,b,c,d,e,h,i){var g=false;g=g||function(f,l,m,o,j,k){f=/([0-9]+).([0-9]+)/.exec(k);if(j=="Android"&&f){j=parseInt(f[1]);f=parseInt(f[2]);return j>2||j==2&&f>=2}else return false}(a,b,c,d,e,h,i);if(!g)return false;return function(f,l,m,o,j){if(f=="Safari"&&m=="AppleWebKit"||f=="Unknown"&&m=="AppleWebKit"&&(j=="iPhone"||j=="iPad"))if(f=/([0-9]+.[0-9]+)/.exec(o))return parseFloat(f[1])>=525.13;return false}(a,b,c,d,e,h,i)}));
if(!window.Typekit){var pa=new N(false,"use.typekit.com","/"),V=(new s(navigator.userAgent,document)).parse(),W=new K(document,V),X=function(a,b){setTimeout(a,b)},Y=new R(pa,W,V,document.documentElement,X),Z=new T(window,W,X);window.Typekit=Y;window.Typekit.load=Y.load;window.Typekit.addKit=Y.B}var qa,ra=null,sa,$;qa=new N(false,"use.typekit.com","/k");ra=new N(false,function(a){return(a=="https:"?"ssl":"www")+".google-analytics.com"},"");
sa=new function(a,b,c){this.J=a;this.O=b;this.T=c}(null,ra,null);$=new Q("pxc4wor");$.setSecurityToken("3bb2a6e53c9684ffdc9a9bf61b5b2a628b788d2543d3caa13a87032c9cd039c065c4b96892345303e9821224491488fe5eb0d3d20d94ff9b40694e9e70b78a71d6f8512511c8946e96234d6a6311b93d5025ae8765228f5f72e22018fe7be64efa8bd8e683");$.setNestedUrl(qa);$.setKitOptions(sa);
$.addFontFamily(new M('"adelle-1","adelle-2"',{a:["n4","n6"],b:["n4","n6"],c:["n4","n6"],d:["n4","n6"],e:["n4","n6"],f:["n4","n6"],g:["n4","n6"],h:["n4","n6"]}));$.addFontFamily(new M('"league-gothic-1","league-gothic-2"',{a:["n4"],b:["n4"],c:["n4"],d:["n4"],e:["n4"],f:["n4"],g:["n4"],h:["n4"]}));$.addCssRule(new L([".tk-adelle"],[{value:'"adelle-1","adelle-2",serif',name:"font-family"}]));$.addCssRule(new L([".tk-league-gothic"],[{value:'"league-gothic-1","league-gothic-2",sans-serif',name:"font-family"}]));
$.addBrowser(U.getBrowserById("air-linux-osx-win"));$.addBrowser(U.getBrowserById("chrome-linux-osx-win2003-win7-winvista-winxp"));$.addBrowser(U.getBrowserById("chrome6-linux-osx"));$.addBrowser(U.getBrowserById("chrome6-win2003-win7-winvista-winxp"));$.addBrowser(U.getBrowserById("ff35-linux-osx-win2003-win7-winvista-winxp"));$.addBrowser(U.getBrowserById("ff36-linux-osx-win2003-win7-winvista-winxp"));$.addBrowser(U.getBrowserById("ie-win2003-win7-winvista-winxp"));$.addBrowser(U.getBrowserById("ie9-win7"));
$.addBrowser(U.getBrowserById("ie9-winvista"));$.addBrowser(U.getBrowserById("opera-linux-osx-win2003-win7-winvista-winxp"));$.addBrowser(U.getBrowserById("safari-android"));$.addBrowser(U.getBrowserById("safari-osx-win2003-win7-winvista-winxp"));if(Z&&Z.Q.__webfonttypekitmodule__){Z.B($);Z.load()}else window.Typekit.addKit($);
})(this,document);
window.Typekit.config={"p":"//p.typekit.net/p.gif?s=1&k=pxc4wor&ht=tk&h={host}&f=6864.6862.1344&a=293615&_={_}"};
/*{"k":"1.5.7","created":"2013-06-24T11:57:48Z"}*/
;(function(window,document,undefined){
function c(a){return function(){return this[a]}}var f=this;function g(a,b){var d=a.split("."),e=f;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var h;d.length&&(h=d.shift());)!d.length&&void 0!==b?e[h]=b:e=e[h]?e[h]:e[h]={}}function j(a,b,d){this.B=a;this.z=b;this.A=d}g("webfont.BrowserInfo",j);j.prototype.o=c("B");j.prototype.hasWebFontSupport=j.prototype.o;j.prototype.q=c("z");j.prototype.hasWebKitFallbackBug=j.prototype.q;j.prototype.r=c("A");j.prototype.hasWebKitMetricsBug=j.prototype.r;
function k(a,b,d,e,h,p,q,r,s,t,u){this.s=a;this.I=b;this.w=d;this.g=e;this.F=h;this.f=p;this.u=q;this.G=r;this.t=s;this.e=t;this.d=u}g("webfont.UserAgent",k);k.prototype.getName=c("s");k.prototype.getName=k.prototype.getName;k.prototype.n=c("w");k.prototype.getVersion=k.prototype.n;k.prototype.j=c("g");k.prototype.getEngine=k.prototype.j;k.prototype.k=c("f");k.prototype.getEngineVersion=k.prototype.k;k.prototype.l=c("u");k.prototype.getPlatform=k.prototype.l;k.prototype.m=c("t");
k.prototype.getPlatformVersion=k.prototype.m;k.prototype.i=c("e");k.prototype.getDocumentMode=k.prototype.i;k.prototype.h=c("d");k.prototype.getBrowserInfo=k.prototype.h;function l(){this.v=window.Typekit.config.p}function m(a,b,d){var e=d||{};a=a.v.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,d){return d&&e[b]?"/"+e[b].join("/"):e[b]||""});a.match(/^\/\//)&&(a=(b?"https:":"http:")+a);return a.replace(/\/*\?*($|\?)/,"$1")}
function n(a){var b=new Image(1,1);b.src=a;b.onload=function(){b.onload=null}}window.Typekit||(window.Typekit={});var v=new function(a,b){this.b=a;this.a=b||a;this.D=this.a.document;this.H=void 0}(window),w=new function(){var a=new l;this.C=null;this.c=a},x=!1;
function y(){if(!x)for(var a=document.getElementsByTagName("link"),b=0;b<a.length;b++){var d=a[b].getAttribute("href");if(d&&0<=d.indexOf("use.typekit")){a=w;b=v;if(a.c){var d=(d=window.__adobewebfontsappname__)?d.toString().substr(0,20):"",e=b.a.location.protocol;"about:"==e&&(e=b.b.location.protocol);n(m(a.c,"https:"===("https:"==e?"https:":"http:"),{host:encodeURIComponent(b.a.location.hostname||b.b.location.hostname),app:encodeURIComponent(d),_:(+new Date).toString()}))}x=!0;break}}}var z=window.Typekit.load;
window.Typekit.load=function(){z&&z.apply(window.Typekit,arguments);y()};window.__webfonttypekitmodule__&&y();
})(this,document);
